version: 1
accounts:
  - name: alice
    coins:
      - 20000elys
      - 200000000stake
  - name: bob
    coins:
      - 10000elys
      - 100000000stake
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 5elys
    - 100000stake
validators:
  - name: alice
    bonded: 100000000stake
